#!/bin/bash

BB=`ifconfig en0 | egrep -o 'broadcast ([0-9]{1,3}\.){3}[0-9]{1,3}'  | cut -d' ' -f2`
echo ${BB}

ping ${BB} -t 1 >/dev/null 2>&1
arp -a | grep `echo "${BB//.255}"` | cut -d')' -f 1 | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -vB 1 "${BB}"