#!/bin/bash
DIR=$1
FILECOUNT=$2

if [ -z "${DIR}" ] || [ -z "${FILECOUNT}" ]
then
	echo "usage: sh 03 <directory> <file count>"
	exit 1
fi

if [ ! -d "${DIR}" ]; then mkdir -p "${DIR}"; fi
cd "${DIR}"/ || exit 1

for (( i=01; i<=FILECOUNT; i++ ))
do
	FILE=$(printf "%02d" "$i")
	touch "$FILE"
done

